import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
// import { Almarai } from "next/font/google";

const Arabic = localFont({
  src: [
    {
      path: "Fonts/NotoKufiArabic-Black.ttf",
      weight: "900",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-ExtraBold.ttf",
      weight: "800",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-SemiBold.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Medium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Light.ttf",
      weight: "300",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Thin.ttf",
      weight: "200",
      style: "normal"
    },
  ],
  variable: "--font-arabic",
  display: "swap",
  declarations: [
    {
      prop: "font-feature-settings",
      value: '"liga", "calt", "kern"',
    },
  ],
});

// const Arabic = Almarai({
//   subsets: ["arabic"],
//   weight: ["800"],
//   variable: "--font-arabic",
//   display: "swap",
// })


export const metadata: Metadata = {
  title: "EgCima",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="auto"
        className={`${Arabic.className} antialiased bg-background min-h-screen max-w-screen overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
