import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Footer from "./components/Footer";
import { Orbitron } from "next/font/google";
import Navbar from "./components/Navbar";

const Arabic = localFont({
  src: [
    {
      path: "Fonts/NotoKufiArabic-Black.ttf",
      weight: "900",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-ExtraBold.ttf",
      weight: "800",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-SemiBold.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Medium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Light.ttf",
      weight: "300",
      style: "normal"
    },
    {
      path: "Fonts/NotoKufiArabic-Thin.ttf",
      weight: "200",
      style: "normal"
    },
  ],
  variable: "--font-arabic",
  display: "swap",
  declarations: [
    {
      prop: "font-feature-settings",
      value: '"liga", "calt", "kern"',
    },
  ],
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-orbitron",
  display: "swap",
})



export const metadata: Metadata = {
  title: "TEMDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="auto"
        className={`${Arabic.className} ${orbitron.variable} antialiased bg-background min-h-screen max-w-screen overflow-x-hidden`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
